/**
 * Task Tracker Data
 * Auto-generated from data/task-tracker.csv
 * Last updated: 2025-11-21T14:52:38.817Z
 *
 * DO NOT EDIT MANUALLY - Run: npx tsx lib/parse-task-csv.ts
 */

import type { Task } from './task-tracker-types';

export const tasks: Task[] = [
  {
    "id": "product-dev-product-roadmap",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "Product Roadmap",
    "description": "Prepare and update the MVP and associated product roadmap bi-weekly for the team, focusing on architecture decisions, including multilingual support for future scope. (Kicked off at the workshop on 10 November; see Product Roadmap file for details.)",
    "whyItMatters": "Manage stakeholder expectations: Defining the product features in scope for MVP (early December), Pilot Testing (mid-January), the Enterprise Product (early April), and Future Scope.",
    "latestUpdate": "Product Roadmap Review: Agreed 2-3 week cadence. Next reviews: 24 November (Pre-MVP Test) and 10 December (Post-MVP Test). Baresquare to prepare, facilitate, and document.",
    "adidasComments": "",
    "startDate": "31-Oct",
    "durationWeeks": 21,
    "endDate": "27-Mar",
    "lead": "baresquare",
    "status": "On Track",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-updated-ui-mini-test-",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "Updated UI \n(Mini Test)",
    "description": "Baresquare is working with a designer to prepare the updated version based on the consolidated and prioritized feedback within the next 2 weeks - we have almost everything we need",
    "whyItMatters": "Finalising the validated user interface design is a mandatory prerequisite for completing the work necessary for the Pilot Testing in Jan./Feb., keeping the project on track for the April Enterprise Go-Live.",
    "latestUpdate": "Changes Implemented: All functional, copy, and quick-win changes are now complete based on feedback. UI Revamp: Brief shared with external designer (15 Nov); ETA 26 Nov. Code Testing Exception: Implemented to allow all users (assigned to 'Director' cohort) to complete the self-reflection.",
    "adidasComments": "",
    "startDate": "14-Nov",
    "durationWeeks": 2,
    "endDate": "28-Nov",
    "lead": "baresquare",
    "status": "On Track",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-updated-ui-mini-test-",
    "completed": true,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "Updated UI \n(Mini Test)",
    "description": "Quick feedback: a) pillar images b) full stops c) remove the wave hand emoji from the welcome screen? d) links to be 100% sure e) 24 and not 23 questions f) micro actions introduction (YES/NO)?",
    "whyItMatters": "Validated UX and functionality is a prerequisite for completing the UI design / update in the next 2 weeks (for the Mini Testing)",
    "latestUpdate": "Completed",
    "adidasComments": "",
    "startDate": "14-Nov",
    "durationWeeks": 0,
    "endDate": "14-Nov",
    "lead": "baresquare",
    "status": "Completed",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-micro-actions-v3-review-mini-test-",
    "completed": true,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "Micro-Actions v3 review (Mini Test)",
    "description": "Review if micro actions provide useful leadership recommendations, contain words/languages not suitable for adidas, or miss words/languages not suitable for adidas",
    "whyItMatters": "Micro-actions are the core of the LSR tool. They have to be relevant for the related leadership cohort, relate to the the self-reflection input the user gave, and align with the adidas tone and voice",
    "latestUpdate": "Completed",
    "adidasComments": "",
    "startDate": "28-Oct",
    "durationWeeks": 2.3,
    "endDate": "13-Nov",
    "lead": "adidas",
    "status": "Completed",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-ratings-pilot-",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "PRODUCT DEV",
    "title": "Ratings (Pilot)",
    "description": "Confirm requirements for “Thumbs up/down” and other (optional) feedback functionality for Micro-Actions and Learning Recommendations.",
    "whyItMatters": "Providing users with an easy way to give feedback on the tool’s usability and usefulness enables adidas and the product team to collect insights at scale. This is critical to ensuring an excellent user experience (UX) and informing future enhancements.",
    "latestUpdate": "Feature Feedback Mechanism: MVP feature (Thumbs Up/Down, optional comments) approved for early rollout. Privacy Confirmed: Feedback is anonymous and stored without personal identifiers. Action: Copy confirmed, pending quick bug fix on language settings (Nikos to resolve). Future: Analytics/sentiment analysis planned for later.",
    "adidasComments": "",
    "startDate": "17-Nov",
    "durationWeeks": 4,
    "endDate": "15-Dec",
    "lead": "baresquare",
    "status": "On Track",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-product-version-control-new-feature-ux-request-",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "Product Version Control (New Feature/UX request)",
    "description": "Investigate if version control and tracking mechanism for Micro Actions product iterations is needed. Out of scope for \"Mini Testing\"",
    "whyItMatters": "Provide visibility and historical tracking to Adidas post-go-live.",
    "latestUpdate": "Not discussed on 19 Nov. Cover at Product Review on 24 Nov. or regular Weely PJ recap on 27 Nov.",
    "adidasComments": "",
    "startDate": "1-Dec",
    "durationWeeks": 6,
    "endDate": "12-Jan",
    "lead": "baresquare",
    "status": "Not Started",
    "ownerAdidas": "Divya",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-system-integration-test",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "PRODUCT DEV",
    "title": "System Integration Test",
    "description": "System Integration Testing (SIT): Migrate and test Pilot app from baresquare to adidas technical environment, including service account user setup and stress testing.",
    "whyItMatters": "Provide confidence to adidas users that the LSRT works securely and adhering to privacy rules on the adidas tech stack.",
    "latestUpdate": "MVP Deployment Status: MVP version is now deployed onto the Adidas environment. Next Step: Pair programming session with Lucas this Friday to review publishing/sharing options. This session will determine if mini-testing proceeds with Plan A (Adidas env) or Plan B (Baresquare env).",
    "adidasComments": "",
    "startDate": "17-Nov",
    "durationWeeks": 4,
    "endDate": "15-Dec",
    "lead": "baresquare",
    "status": "On Track",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "product-dev-lf-questions-all-cohorts",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "PRODUCT DEV",
    "title": "LF questions all cohorts",
    "description": "Develop and finalise the Leadership Framework (LF) questions tailored for the Executive, Manager, and Team Lead leadership cohorts.",
    "whyItMatters": "Preparing and testing the full range of questions is necessary to ensure the LSRT's content is scalable, relevant, and accurate across all key user segments. This validation confirms the technical and functional stability of the application beyond the Director cohort, which is mandatory for a successful Enterprise Go-Live.",
    "latestUpdate": "Enterprise Product Timeline: Baresquare requires the LF questions by cohort to be finalised by adidas by end January to ensure the Enterprise Product is ready by end March. Adidas confirmed LF will contain roughly 20-30 questions per cohort, with 3-5 being cohort-specific, and acknowledged the January deadline.",
    "adidasComments": "",
    "startDate": "17-Nov",
    "durationWeeks": 10,
    "endDate": "26-Jan",
    "lead": "adidas",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "change-requests-german-language",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "CHANGE REQUESTS",
    "title": "German language",
    "description": "German language requirement / budget: Confirm by mid-December, if DE language is required for Enterprise go-live.",
    "whyItMatters": "LSRT cannot go live in Germany without Workers Council approval. As the Council is highly likely to mandate a German language version, the project requires the associated Change Request (budget) to be approved by mid-December ideally to plan ressources for the April go-live date.",
    "latestUpdate": "German LSRT Version: Adidas confirmed German LSRT can wait until the Enterprise go-live (April readiness). Budget Constraint: Adidas stated no new budgets/Change Requests can be confirmed before mid January. \n\nBSQ Commitment: Baresquare can deliver the German version for an April Enterprise product readiness only if the related budget is approved and Change Request is signed by end January.",
    "adidasComments": "",
    "startDate": "4-Sep",
    "durationWeeks": 20,
    "endDate": "22-Jan",
    "lead": "adidas",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "change-requests-ic-values-self-reflection-tool",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "CHANGE REQUESTS",
    "title": "IC-Values Self-Reflection Tool",
    "description": "IC Self-Reflection Tool: Confirm business requirements by end-November. Facilitate the adidas budget approval process (Change Request).",
    "whyItMatters": "Timely confirmation allows baresquare to propose a cost-effective solution, enabling the IC Self-Reflection Tool to launch with LSRT or shortly thereafter. Confirming requirements by end-November enables the Change Request quotation by December 6th. If the budget is confirmed by mid-January, baresquare can deliver a solution ready for go-live in April, aligning with the LSRT launch date.",
    "latestUpdate": "IC-SRT Requirements: High-level business requirements and direction review agreed for 25 November. Baresquare to share requirements questions with Zsofia beforehand. This understanding is needed to provide a realistic budget/timeline estimate and confirm if a IC-SRT April Enterprise product readiness is feasible (contingent on budget approval/Change Request by end January).",
    "adidasComments": "",
    "startDate": "25-Nov",
    "durationWeeks": 9,
    "endDate": "27-Jan",
    "lead": "adidas",
    "status": "On Watch",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "change-requests-other-languages",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "CHANGE REQUESTS",
    "title": "Other languages",
    "description": "Secure budget approval for implementation of additional languages (“Other”).\nAim to complete this by mid-January if languages beyond English (EN) and German (DE) are required shortly after the Enterprise go-live (assumed go-live: July 2026).",
    "whyItMatters": "Completing a self-reflection in one’s local language is more engaging and impactful than doing so in a foreign language.\nOffering local languages also aligns with our goal of empowering individual markets.",
    "latestUpdate": "Additional Languages & Governance: Adidas suggests grouping this with the January change requests. Crucial Requirement: A clear roll-out and governance model is needed for approval, detailing local HR's role (e.g., implementing new languages, monitoring user comments).\n\nBSQ Comment: Languages beyond English/German require dedicated scoping and budgeting. We assume these are a requirement for Q3 earliest.",
    "adidasComments": "",
    "startDate": "14-Nov",
    "durationWeeks": 9,
    "endDate": "16-Jan",
    "lead": "adidas",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "product-dev-review-before-submit-page-new-feauture-ux-request-",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "PRODUCT DEV",
    "title": "Review before submit page (New Feauture/UX request)",
    "description": "Investigate the idea of introducing a final submission step and come back to Zsofia with an effort/complexity estimation to decide if and when this could be implemented.",
    "whyItMatters": "This step should include all questions and comments, and users should be able to add/edit their scores and comments before submitting their self-reflection",
    "latestUpdate": "Not discussed on 19 Nov. Cover at Product Review on 24 Nov. or regular Weely PJ recap on 27 Nov.",
    "adidasComments": "",
    "startDate": "17-Nov",
    "durationWeeks": 4,
    "endDate": "15-Dec",
    "lead": "baresquare",
    "status": "On Watch",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "project-admin-phase-1-billing",
    "completed": true,
    "weeklyFocus": true,
    "workstream": "PROJECT ADMIN",
    "title": "Phase 1 billing",
    "description": "Confirm SAP \"Goods Receipt\" for LSRT Phase 1 by December 5th (invoice to be sent by baresquare by November 28, 2025)",
    "whyItMatters": "Make sure adidas Accounting team can close FY25 books correctly (see mail adidas GBS sent on 11.11.2025)",
    "latestUpdate": "This item is completed from adidas side.",
    "adidasComments": "",
    "startDate": "28-Nov",
    "durationWeeks": 1,
    "endDate": "5-Dec",
    "lead": "adidas",
    "status": "Completed",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "user-testing-mini-testing",
    "completed": true,
    "weeklyFocus": false,
    "workstream": "USER TESTING",
    "title": "Mini Testing",
    "description": "Provide a “mini testing” approach/brief and confirm proposed dates (assume December 2nd & 3rd) for on-site usability testing (5–8 Directors at adidas-Herzo, first week of December). Assume 75 minutes per particpant. Provide a more detailed testing approach to be reviewed on Tuesday 18-Nov (Lars to set up call with Zsofia).",
    "whyItMatters": "Testing with 5 Directors ideally outside the Global HR department provides impartial feedback on tool usability and usefulness. Usability reasearch has shown that 5 users oncover already 85% of usability issues. It is critical for the project success to validate the pilot professionally before it goes to more extensive testing with 40-50 directors.",
    "latestUpdate": "Testing dates and HL approach for December 2nd & 3rd. 5-8 Directors; detailed test plan shared",
    "adidasComments": "",
    "startDate": "7-Nov",
    "durationWeeks": 1.6,
    "endDate": "18-Nov",
    "lead": "baresquare",
    "status": "Completed",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "user-testing-mini-testing",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "USER TESTING",
    "title": "Mini Testing",
    "description": "Manage director selection for the early Usability Testing cohort and plan logistics for the onsite sessions (5-8 directors, first week of December).",
    "whyItMatters": "Targeted selection of 5-8 directors for early usability testing is key to discovering 85–90% of core usability issues prior to the large-scale Pilot Testing (40+ directors) scheduled for January/February.",
    "latestUpdate": "MVP Mini Testing (adidas prep): Adidas to confirm and invite participants and confirm meeting room details. Participants must be asked to bring their personal work computer and seek consent to record the session.",
    "adidasComments": "",
    "startDate": "14-Nov",
    "durationWeeks": 2,
    "endDate": "28-Nov",
    "lead": "adidas",
    "status": "On Track",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "user-testing-mini-testing",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "USER TESTING",
    "title": "Mini Testing",
    "description": "Prepare \"Mini Testing\" documentation and presentation a) for project team and b) for HR SLT",
    "whyItMatters": "Basis for a) roadmap review (i.e. Feature/UX change prioritization for Pilot Testing and Go-Live) and b) providing visibility to HR SLT on project progress and employee user feedback",
    "latestUpdate": "MVP Mini Testing (baresquare prep): Baresquare to prepare user testing details (questions, specialist facilitator, recording set-up), assuming the MVP test will run on the adidas network (\"Plan A\").",
    "adidasComments": "",
    "startDate": "4-Dec",
    "durationWeeks": 1,
    "endDate": "11-Dec",
    "lead": "baresquare",
    "status": "On Track",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "user-testing-pilot-testing",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "USER TESTING",
    "title": "Pilot Testing",
    "description": "Finalise the Pilot Testing approach, brief, and schedule (mid-January to mid-February 2026). Execute large-scale remote user testing (40–50 Directors) and deep-dive interviews (10–12 Directors), specifically including Global HR members for advanced functional feedback.",
    "whyItMatters": "This large-scale pilot is essential for project success as it provides comprehensive, real-world validation across 40–50 directors prior to the April Enterprise go-live. Critically, it also serves to establish an initial cohort of tool promoters and champions, ensuring positive early adoption and advocacy across the organisation.",
    "latestUpdate": "Pilot Test Plan: Plan including questions has been submitted from Baresquare to Adidas. Needs review again after MVP Testing is completed, ideally by mid-December.",
    "adidasComments": "",
    "startDate": "27-Oct",
    "durationWeeks": 6,
    "endDate": "8-Dec",
    "lead": "baresquare",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "user-testing-pilot-testing",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "USER TESTING",
    "title": "Pilot Testing",
    "description": "Manage director selection for the Pilot Testing cohort and plan all adidas logistics for the remote sessions (40–50 Directors, mid-January to mid-February).",
    "whyItMatters": "Successful Pilot Testing is a critical path dependency that must be satisfied before the project can proceed to Phase 2 Enterprise Go-Live.",
    "latestUpdate": "Pilot Test Plan: Plan including questions has been submitted from Baresquare to Adidas. Needs review again after MVP Testing is completed, ideally by mid-December.",
    "adidasComments": "",
    "startDate": "8-Dec",
    "durationWeeks": 4,
    "endDate": "5-Jan",
    "lead": "adidas",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "stakeholder-mgt--workers-council",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "STAKEHOLDER MGT.",
    "title": "Workers Council",
    "description": "Initiate and manage the Workers Council approval process immediately following Pilot readiness (assumed mid January). Allocate eight weeks to secure approval prior to the Enterprise Go-Live date.",
    "whyItMatters": "The LSRT cannot go live in Germany without formal Workers Council approval. Securing this approval is a mandatory regulatory dependency for the Enterprise phase.",
    "latestUpdate": "Adidas confirmed this task end date can be later than 21 January; WoCo approval is secured for pilot/mini-testing (but required prior to go-live day). \n\nBaresquare Action: Re-schedule and re-phrase for the Enterprise phase",
    "adidasComments": "",
    "startDate": "14-Jan",
    "durationWeeks": 8,
    "endDate": "11-Mar",
    "lead": "adidas",
    "status": "Paused",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "stakeholder-mgt--infosec",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "STAKEHOLDER MGT.",
    "title": "InfoSec",
    "description": "Secure adidas InfoSec Team agreement to finalise the LeanIX approval entry. (The LeanIX entry exists, but the official sign-off is pending this agreement).",
    "whyItMatters": "The LSRT cannot proceed to go-live without mandatory LeanIX approval secured via the Enterprise Architect. This approval is a non-negotiable technical dependency.",
    "latestUpdate": "InfSec Approval (\"In Progress\"): Project Go Live must be confirmed by InfSec. We assume no major concerns as the adidas tech stack is used. Crucial Timeline: InfSec confirmation is a critical input for the Workers Council before Enterprise Go Live, therefore aim for confirmation by end January.",
    "adidasComments": "",
    "startDate": "1-Sep",
    "durationWeeks": 21,
    "endDate": "26-Jan",
    "lead": "adidas",
    "status": "On Watch",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "stakeholder-mgt--privacy",
    "completed": false,
    "weeklyFocus": true,
    "workstream": "STAKEHOLDER MGT.",
    "title": "Privacy",
    "description": "Obtain adidas-Privacy-Team agreement for LeanIX approval (LeanIX entry already there, but official approcal missing)",
    "whyItMatters": "The LSRT cannot proceed to go-live without mandatory LeanIX approval secured via the Enterprise Architect. This approval is a non-negotiable technical dependency.",
    "latestUpdate": "Privacy, Data Storage, & Feature Compliance: \n\n1./ Download PDF feature is approved. \n\n2./ Other key features (saving in-progress responses and past submissions) require a Data Privacy Assessment due to storage of unique identifiers/personal data. \n\nAction: \n- Lukas to trigger formal Privacy Assessment process now; aiming for completion by mid of February, well in time for Enterprise go-live compliance. Confirm if this is critical input for Workers Council as well (same as InfoSec)\n- MVP Mini Testing can proceed without the saving feature fully approved.",
    "adidasComments": "",
    "startDate": "16-Oct",
    "durationWeeks": 17,
    "endDate": "12-Feb",
    "lead": "adidas",
    "status": "On Watch",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "content-ops-learning-recs-pilot-",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "CONTENT OPS",
    "title": "Learning Recs (Pilot)",
    "description": "Have a topical meeting with Frederike to confirm the status and completion of the \"Learning Assets\" file (mapping LiL Courses to Proficiency-Skill-Level). Once confirmed, executing the mapping of the \"Learning Assets\" file to the Leadership Framework taxonomy.",
    "whyItMatters": "The LSRT requires useful, integrated learning recommendations that are fully aligned with the Leadership Framework to drive user adoption and value. This mapping is essential for the LSRT to connect effectively with the Learning Agent application.",
    "latestUpdate": "Learning Recommendations: New Mapping Files provided by Zsofia (18 Nov), to be studied by Baresquare. Confirmed Deadlines: Director Cohort (Pilot Testing) deadline is 12 December. Other 3 Cohorts deadline is mid/end January if required for April go-live readiness.",
    "adidasComments": "",
    "startDate": "3-Oct",
    "durationWeeks": 10,
    "endDate": "12-Dec",
    "lead": "adidas",
    "status": "On Watch",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Lars"
  },
  {
    "id": "content-ops-ui-copy-mini-test-",
    "completed": true,
    "weeklyFocus": false,
    "workstream": "CONTENT OPS",
    "title": "UI Copy (Mini Test)",
    "description": "Finalise and obtain sign-off on all user interface (UI) copy for the Mini Testing environment, including securing the official, approved adidas privacy statement text.",
    "whyItMatters": "Confirming the copy, particularly the official privacy statement, is mandatory to ensure the Mini Testing adheres to all internal Data Protection and Compliance requirements. Finalised UI copy also guarantees a professional, unified user experience, preventing confusion and allowing the team to focus solely on usability feedback during the testing phase.",
    "latestUpdate": "Competed for MVP Mini Test version.",
    "adidasComments": "",
    "startDate": "28-Oct",
    "durationWeeks": 4,
    "endDate": "25-Nov",
    "lead": "adidas",
    "status": "Completed",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "content-ops-ui-copy-pilot-",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "CONTENT OPS",
    "title": "UI Copy (Pilot)",
    "description": "Finalise and obtain sign-off on all user interface (UI) copy for the Pilot Testing environment, including securing the official, approved adidas privacy statement text. Assume UI copy revision may happen after Pilot Testing feedback, and Pilot Testing to conclude by mid-Feb.",
    "whyItMatters": "Confirming the copy, particularly the official privacy statement, is mandatory to ensure the Pilot Testing environment adheres to all internal Data Protection and Compliance requirements before Enterprise Go-Live. Finalised UI copy guarantees a professional, unified user experience for the 40–50 directors, preventing confusion and securing positive advocacy prior to launch.",
    "latestUpdate": "Pilot LSRT - UI Copy Re-assessment: UI copy for Pilot Testing will be re-assessed following the MVP Mini-Test, scheduled during the Product Roadmap review on 10 December.",
    "adidasComments": "",
    "startDate": "10-Dec",
    "durationWeeks": 5,
    "endDate": "14-Jan",
    "lead": "adidas",
    "status": "Not Started",
    "ownerAdidas": "Zsofia",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "analytics-analytics-reqs",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "ANALYTICS",
    "title": "Analytics Reqs",
    "description": "Define and confirm the Analytics Strategy for the LSRT MVP (Mini Testing reference).\n\na) Propose essential functional and technical metrics/variables for tracking while ensuring strict adherence to privacy constraints.\nb) Confirm implementation feasibility with the tagging team once Google Analytics (GA) and Tealium are confirmed in the baresquare development environment.",
    "whyItMatters": "Functional and technical analytics are essential for monitoring application stability, performance, and user adoption. For LSRT, we must ensure all data processing is anonymous to maintain privacy compliance, while simultaneously obtaining crucial insights into user behaviour and overall tool usefulness.",
    "latestUpdate": "Analytics Workstream: Resume as soon as the MVP Mini Test production version is finalised and the Privacy Assessment questionnaire is received.",
    "adidasComments": "",
    "startDate": "28-Nov",
    "durationWeeks": 3,
    "endDate": "19-Dec",
    "lead": "baresquare",
    "status": "Paused",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Kassiani"
  },
  {
    "id": "stakeholder-mgt--infosec",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "STAKEHOLDER MGT.",
    "title": "InfoSec",
    "description": "Complete Infossec questionaire",
    "whyItMatters": "Infosec team has to sign-off before Enterprise Architect can approve addidng LA and LSRT apps to adidas (i.e. \"LeanIX entry)",
    "latestUpdate": "InfoSec Vendor Questionnaire: Baresquare may need to prepare a more comprehensive questionnaire due to the latest privacy feedback on key product features (specifically, the 'save progress' and 'latest submission' requirements).",
    "adidasComments": "",
    "startDate": "16-Oct",
    "durationWeeks": 17,
    "endDate": "12-Feb",
    "lead": "baresquare",
    "status": "On Watch",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Nikos"
  },
  {
    "id": "stakeholder-mgt--privacy",
    "completed": false,
    "weeklyFocus": false,
    "workstream": "STAKEHOLDER MGT.",
    "title": "Privacy",
    "description": "Provide Data Protection Officer (DPO) privacy considerations for the following product features: 'save progress,' 'save self-reflection,' and 'anonymized analytics.'",
    "whyItMatters": "Privacy team has to sign-off before Enterprise Architect can approve addidng LA and LSRT apps to adidas (i.e. \"LeanIX entry)",
    "latestUpdate": "Privacy Vendor Questionnaire: Baresquare may need to prepare a more comprehensive questionnaire due to the latest privacy feedback on key product features (specifically, the 'save progress' and 'latest submission' requirements).",
    "adidasComments": "",
    "startDate": "16-Oct",
    "durationWeeks": 17,
    "endDate": "12-Feb",
    "lead": "baresquare",
    "status": "On Watch",
    "ownerAdidas": "Lukas",
    "ownerBaresquare": "Lars"
  }
];

// Helper: Get tasks by workstream
export function getTasksByWorkstream(workstream: string): Task[] {
  return tasks.filter(t => t.workstream === workstream);
}

// Helper: Get weekly focus tasks
export function getWeeklyFocusTasks(): Task[] {
  return tasks.filter(t => t.weeklyFocus);
}

// Helper: Get tasks by status
export function getTasksByStatus(status: string): Task[] {
  return tasks.filter(t => t.status === status);
}

// Helper: Get tasks by lead
export function getTasksByLead(lead: 'adidas' | 'baresquare'): Task[] {
  return tasks.filter(t => t.lead === lead);
}

// Helper: Get active tasks (not completed, not paused)
export function getActiveTasks(): Task[] {
  return tasks.filter(t => !t.completed && t.status !== 'Paused');
}

// Helper: Get task by ID
export function getTaskById(id: string): Task | undefined {
  return tasks.find(t => t.id === id);
}
